"""Add tracker and orbit decay models

Revision ID: a68a1e48c95f
Revises: da10ec576e56
Create Date: 2026-06-30 03:06:41.407558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a68a1e48c95f'
down_revision: Union[str, Sequence[str], None] = 'da10ec576e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('conjunctions',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('primary_norad_id', sa.Integer(), nullable=False),
    sa.Column('secondary_norad_id', sa.Integer(), nullable=False),
    sa.Column('tca_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('miss_distance_km', sa.Float(), nullable=False),
    sa.Column('collision_probability', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conjunctions_primary_norad_id'), 'conjunctions', ['primary_norad_id'], unique=False)
    op.create_table('space_weather',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('f107_index', sa.Float(), nullable=False),
    sa.Column('kp_index', sa.Float(), nullable=False),
    sa.Column('ap_index', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp')
    )
    op.create_table('tle_records',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('epoch_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tle_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tle_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tle_records_norad_id'), 'tle_records', ['norad_id'], unique=False)
    op.alter_column('raw_frames', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('raw_frames', 'station_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('raw_frames', 'raw_frame',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('idx_raw_norad_ts'), table_name='raw_frames')
    op.drop_index(op.f('raw_frames_timestamp_idx'), table_name='raw_frames')
    op.alter_column('telemetry_frames', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('telemetry_frames', 'raw_frame_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('telemetry_frames', 'frame_is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('telemetry_frames', 'missing_raw_fields',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('telemetry_frames', 'dropped_packet_suspect',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telemetry_frames', 'sampling_irregular',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_telem_anomaly'), table_name='telemetry_frames', postgresql_where='(is_anomaly = true)')
    op.drop_index(op.f('idx_telem_norad_ts'), table_name='telemetry_frames')
    op.drop_index(op.f('telemetry_frames_timestamp_idx'), table_name='telemetry_frames')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('telemetry_frames_timestamp_idx'), 'telemetry_frames', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_telem_norad_ts'), 'telemetry_frames', ['norad_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_telem_anomaly'), 'telemetry_frames', ['norad_id', 'is_anomaly', sa.literal_column('timestamp DESC')], unique=False, postgresql_where='(is_anomaly = true)')
    op.alter_column('telemetry_frames', 'sampling_irregular',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('telemetry_frames', 'dropped_packet_suspect',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('telemetry_frames', 'missing_raw_fields',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('telemetry_frames', 'frame_is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('telemetry_frames', 'raw_frame_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('telemetry_frames', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('raw_frames_timestamp_idx'), 'raw_frames', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_raw_norad_ts'), 'raw_frames', ['norad_id', sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('raw_frames', 'raw_frame',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('raw_frames', 'station_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('raw_frames', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tle_records_norad_id'), table_name='tle_records')
    op.drop_table('tle_records')
    op.drop_table('space_weather')
    op.drop_index(op.f('ix_conjunctions_primary_norad_id'), table_name='conjunctions')
    op.drop_table('conjunctions')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
